const asyncWrapper = (fn) => {  //to avoid replication of try-catch in controllers
    return async (req, res, next) => {
        try {
            await fn(req, res, next)
        } catch (error) {
            next(error)
        }
    }
}

module.exports = asyncWrapper;